import { IChainData } from '@/lib/wallet-selector/types';

// walletConnect infura id
export const INFURA_ID = 'c3fbac6d01a74109b3c5088d657f528e';

export const ETH_SUPPORTED_CHAINS: IChainData[] = [
  {
    name: 'Ethereum Mainnet',
    show_chain_name: 'Ethereum',
    chain_icon_bg: `/image/token/eth_bg.png`,
    chain_icon: `/image/token/chain_eth.png`,
    chain_id: 1,
    rpc_url: `https://mainnet.infura.io/v3/${INFURA_ID}`,
    native_currency: { symbol: 'ETH', name: 'Ethereum', decimals: '18' },
    block_explorer_url: 'https://etherscan.io/',
    gas_price_ratio: 1.6,
    transfer_network: 'Ethereum ',
    sdm_wallet: 'ethereum',
    assets_type: 'eth',
    data_chain: 'ethereum',
    wrap_token: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
    is_test: false
  },
  {
    name: 'Ethereum Gorli',
    show_chain_name: 'Ethereum',
    chain_icon_bg: `/image/token/eth_bg.png`,
    chain_icon: `/image/token/chain_eth.png`,
    chain_id: 5,
    rpc_url: `https://goerli.infura.io/v3/${INFURA_ID}`,
    native_currency: { symbol: 'ETH', name: 'Ethereum', decimals: '18' },
    block_explorer_url: 'https://goerli.etherscan.io/',
    gas_price_ratio: 2,
    transfer_network: 'Ethereum ',
    sdm_wallet: 'ethereum',
    assets_type: 'eth',
    data_chain: 'eth-goerli',
    wrap_token: '0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6',
    is_test: true
  },
  {
    name: 'Ethereum Sepolia',
    show_chain_name: 'Ethereum',
    chain_icon_bg: `/image/token/eth_bg.png`,
    chain_icon: `/image/token/chain_eth.png`,
    chain_id: 11155111,
    rpc_url: `https://sepolia.infura.io/v3/${INFURA_ID}`,
    native_currency: { symbol: 'ETH', name: 'Ethereum', decimals: '18' },
    block_explorer_url: 'https://sepolia.etherscan.io/',
    gas_price_ratio: 1.5,
    transfer_network: 'Ethereum ',
    sdm_wallet: 'ethereum',
    assets_type: 'eth',
    data_chain: 'eth-sepolia',
    wrap_token: '0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6',
    is_test: true
  },
  {
    name: 'Binance Smart Chain',
    show_chain_name: 'BNB',
    chain_icon_bg: `/image/token/chain_bnb.png`,
    chain_icon: `/image/token/chain_bnb.png`,
    chain_id: 56,
    rpc_url: 'https://bsc-dataseed.binance.org/',
    native_currency: { symbol: 'BNB', name: 'BNB', decimals: 18 },
    block_explorer_url: 'https://bscscan.com/',
    gas_price_ratio: 2,
    transfer_network: 'BNB',
    sdm_wallet: 'binance-smart-chain',
    assets_type: 'bnb',
    data_chain: 'binance-smart-chain',
    wrap_token: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c',
    is_test: false
  },
  {
    name: 'Polygon Mainnet',
    show_chain_name: 'Polygon',
    chain_icon_bg: `/image/token/chain_polygon.png`,
    chain_icon: `/image/token/chain_polygon.png`,
    chain_id: 137,
    rpc_url: `https://polygon-mainnet.infura.io/v3/${INFURA_ID}`,
    native_currency: { symbol: 'MATIC', name: 'Matic Token', decimals: 18 },
    block_explorer_url: 'https://polygonscan.com/',
    gas_price_ratio: 4,
    transfer_network: 'Polygon',
    sdm_wallet: 'polygon',
    assets_type: 'polygon',
    data_chain: 'polygon',
    wrap_token: '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270',
    is_test: false
  },
  {
    name: 'Mumbai',
    show_chain_name: 'Polygon',
    chain_icon_bg: `/image/token/chain_polygon.png`,
    chain_icon: `/image/token/chain_polygon.png`,
    chain_id: 80001,
    rpc_url: `https://polygon-mumbai.infura.io/v3/${INFURA_ID}`,
    native_currency: { symbol: 'MATIC', name: 'Matic Token', decimals: 18 },
    block_explorer_url: 'https://mumbai.polygonscan.com/',
    gas_price_ratio: 10,
    transfer_network: 'Polygon',
    sdm_wallet: 'polygon',
    assets_type: 'polygon',
    data_chain: 'polygon-mumbai',
    wrap_token: '0x9c3C9283D3e44854697Cd22D3Faa240Cfb032889',
    is_test: true
  },
  {
    name: 'Amoy',
    show_chain_name: 'Polygon',
    chain_icon_bg: `/image/token/chain_polygon.png`,
    chain_icon: `/image/token/chain_polygon.png`,
    chain_id: 80002,
    rpc_url: `https://polygon-amoy.infura.io/v3/${INFURA_ID}`,
    native_currency: { symbol: 'MATIC', name: 'Matic Token', decimals: 18 },
    block_explorer_url: 'https://amoy.polygonscan.com/',
    gas_price_ratio: 10,
    transfer_network: 'Polygon',
    sdm_wallet: 'polygon',
    assets_type: 'polygon',
    data_chain: 'polygon-amoy',
    wrap_token: '0x9c3C9283D3e44854697Cd22D3Faa240Cfb032889',
    is_test: true
  },
  {
    name: 'Arbitrum',
    show_chain_name: 'Arbitrum',
    chain_icon_bg: `/image/token/chain_arbitrum.png`,
    chain_icon: `/image/token/chain_arbitrum.png`,
    chain_id: 42161,
    rpc_url: `https://arbitrum-mainnet.infura.io/v3/${INFURA_ID}`,
    native_currency: { symbol: 'ETH', name: 'Ethereum', decimals: 18 },
    block_explorer_url: 'https://arbiscan.io/',
    gas_price_ratio: 2,
    transfer_network: 'Arbitrum',
    sdm_wallet: 'arbitrum',
    assets_type: 'arbitrum',
    data_chain: 'arbitrum',
    wrap_token: '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1',
    is_test: false
  },
  {
    name: 'Arbitrum-goerli',
    show_chain_name: 'Arbitrum',
    chain_icon_bg: `/image/token/chain_arbitrum.png`,
    chain_icon: `/image/token/chain_arbitrum.png`,
    chain_id: 421613,
    rpc_url: 'https://goerli-rollup.arbitrum.io/rpc',
    native_currency: { symbol: 'ETH', name: 'Ethereum', decimals: 18 },
    block_explorer_url: 'https://goerli.arbiscan.io/',
    gas_price_ratio: 2,
    transfer_network: 'Arbitrum',
    sdm_wallet: 'arbitrum',
    assets_type: 'arbitrum',
    data_chain: 'arb-goerli',
    wrap_token: '0xe39Ab88f8A4777030A534146A9Ca3B52bd5D43A3',
    is_test: true
  },
  {
    name: 'Arbitrum-sepolia',
    show_chain_name: 'Arbitrum',
    chain_icon_bg: `/image/token/chain_arbitrum.png`,
    chain_icon: `/image/token/chain_arbitrum.png`,
    chain_id: 421614,
    rpc_url: 'https://sepolia-rollup.arbitrum.io/rpc',
    native_currency: { symbol: 'ETH', name: 'Ethereum', decimals: 18 },
    block_explorer_url: 'https://sepolia.arbiscan.io/',
    gas_price_ratio: 2,
    transfer_network: 'Arbitrum',
    sdm_wallet: 'arbitrum',
    assets_type: 'arbitrum',
    data_chain: 'arb-sepolia',
    wrap_token: '0xe39Ab88f8A4777030A534146A9Ca3B52bd5D43A3',
    is_test: true
  },
  {
    name: 'Binance Smart Chain',
    show_chain_name: 'BNB',
    chain_icon_bg: `/image/token/chain_bnb.png`,
    chain_icon: `/image/token/chain_bnb.png`,
    chain_id: 97,
    rpc_url: 'https://data-seed-prebsc-1-s2.binance.org:8545',
    native_currency: { symbol: 'tBNB', name: 'tBNB', decimals: 18 },
    block_explorer_url: 'https://testnet.bscscan.com/',
    gas_price_ratio: 2,
    transfer_network: 'bsc',
    sdm_wallet: 'binance-smart-chain',
    assets_type: 'bnb',
    data_chain: 'binance-testnet',
    wrap_token: '0x161ab8635b28a2f190b3f696877a435a032ab1c1',
    is_test: true
  },
  {
    name: 'Linea-sepolia',
    show_chain_name: 'Linea',
    chain_icon_bg: `/image/token/chain_linea.png`,
    chain_icon: `/image/token/chain_linea.png`,
    chain_id: 59141,
    rpc_url: `https://rpc.sepolia.linea.build/`,
    native_currency: { symbol: 'ETH', name: 'Ethereum', decimals: 18 },
    block_explorer_url: 'https://sepolia.lineascan.build/',
    gas_price_ratio: 1.5,
    transfer_network: 'Linea',
    sdm_wallet: 'linea',
    assets_type: 'linea',
    data_chain: 'linea-sepolia',
    wrap_token: '',
    is_test: true
  },
  {
    name: 'Linea-goerli',
    show_chain_name: 'Linea',
    chain_icon_bg: `/image/token/chain_linea.png`,
    chain_icon: `/image/token/chain_linea.png`,
    chain_id: 59140,
    rpc_url: `https://linea-goerli.infura.io/v3/${INFURA_ID}`,
    native_currency: { symbol: 'ETH', name: 'Ethereum', decimals: 18 },
    block_explorer_url: 'https://goerli.lineascan.build/',
    gas_price_ratio: 1.5,
    transfer_network: 'Linea',
    sdm_wallet: 'linea',
    assets_type: 'linea',
    data_chain: 'linea-goerli',
    wrap_token: '',
    is_test: true
  },
  {
    name: 'Linea',
    show_chain_name: 'Linea',
    chain_icon_bg: `/image/token/chain_linea.png`,
    chain_icon: `/image/token/chain_linea.png`,
    chain_id: 59144,
    rpc_url: `https://linea-mainnet.infura.io/v3/${INFURA_ID}`,
    native_currency: { symbol: 'ETH', name: 'Ethereum', decimals: 18 },
    block_explorer_url: 'https://lineascan.build/',
    gas_price_ratio: 1,
    transfer_network: 'Linea',
    sdm_wallet: 'linea',
    assets_type: 'linea',
    data_chain: 'linea',
    wrap_token: '',
    is_test: false
  },
  {
    name: 'OP Mainnet',
    show_chain_name: 'Optimism',
    chain_icon_bg: `/image/token/chain_optimism.png`,
    chain_icon: `/image/token/chain_optimism.png`,
    chain_id: 10,
    rpc_url: `https://mainnet.optimism.io`,
    native_currency: { symbol: 'ETH', name: 'Ethereum', decimals: 18 },
    block_explorer_url: 'https://optimistic.etherscan.io/',
    gas_price_ratio: 1,
    transfer_network: 'Optimism',
    sdm_wallet: 'optimism',
    assets_type: 'optimism',
    data_chain: 'optimism',
    wrap_token: '',
    is_test: false
  },
  {
    name: 'OP Sepolia Testnet',
    show_chain_name: 'Optimism',
    chain_icon_bg: `/image/token/chain_optimism.png`,
    chain_icon: `/image/token/chain_optimism.png`,
    chain_id: 11155420,
    rpc_url: `https://sepolia.optimism.io`,
    native_currency: { symbol: 'ETH', name: 'Ethereum', decimals: 18 },
    block_explorer_url: 'https://sepolia-optimistic.etherscan.io/',
    gas_price_ratio: 1,
    transfer_network: 'Optimism',
    sdm_wallet: 'optimism',
    assets_type: 'optimism',
    data_chain: 'optimism-sepolia',
    wrap_token: '',
    is_test: true
  }
];
